'use strict';
const $=id=>document.getElementById(id);
const screens={menu:$('menu'),chars:$('charsScreen'),shop:$('shopScreen'),settings:$('settingsScreen'),game:$('game')};
const SAVE='adventureEscapeSaveV2';
const defaults={coins:0,level:1,owned:{gold:false,speed:false,shield:false,forest:false},sfx:true};
let save=load();
function load(){try{const x=JSON.parse(localStorage.getItem(SAVE)||'null')||{};return {...defaults,...x,owned:{...defaults.owned,...(x.owned||{})}}}catch{return JSON.parse(JSON.stringify(defaults))}}
function persist(){localStorage.setItem(SAVE,JSON.stringify(save));sync()}
function sync(){if($('menuCoins'))$('menuCoins').textContent=save.coins;if($('shopCoins'))$('shopCoins').textContent=save.coins;if($('menuLevel'))$('menuLevel').textContent=save.level;if($('level'))$('level').textContent=save.level;if($('coins'))$('coins').textContent=save.coins;if($('sfx'))$('sfx').checked=!!save.sfx;document.querySelectorAll('.item').forEach(c=>{const b=c.querySelector('button'),o=!!save.owned[c.dataset.item];b.textContent=o?'✓ OWNED':'🪙 '+c.dataset.price;c.classList.toggle('owned',o)})}
function show(name){Object.values(screens).forEach(s=>s.classList.add('hidden'));screens[name].classList.remove('hidden')}
let audio=null;function beep(f=500){if(!save.sfx)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.035;o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.07)}catch{}}
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('toastShow');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('toastShow'),1500)}
$('play').onclick=()=>startGame();$('chars').onclick=()=>show('chars');$('shop').onclick=()=>show('shop');$('settings').onclick=()=>show('settings');document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show('menu'));$('sfx').onchange=e=>{save.sfx=e.target.checked;persist()};$('reset').onclick=()=>{localStorage.removeItem(SAVE);save=load();sync();toast('Save reset')};
document.querySelectorAll('.item').forEach(c=>c.onclick=e=>{if(e.target.tagName!=='BUTTON')return;const k=c.dataset.item,p=+c.dataset.price;if(save.owned[k])return;if(save.coins<p){toast('Not enough coins');return}save.coins-=p;save.owned[k]=true;persist();beep(800);toast('Purchased!')});
let ctx=null,game=false,paused=false,raf=0,last=0,worldTime=0;const keys=Object.create(null);const P={x:0,y:0,vx:0,vy:0,health:100,runCoins:0,dash:0,inv:0,onGround:true,face:1,step:0};let beast={x:0,y:-550,awake:false,timer:0};let coins=[],particles=[],trees=[];
function resize(){if(!ctx)return;const d=Math.min(2,devicePixelRatio||1);ctx.canvas.width=innerWidth*d;ctx.canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}
function init(){if(ctx)return;ctx=$('gameCanvas').getContext('2d');resize();addEventListener('resize',resize);}
function startGame(){init();show('game');game=true;paused=false;P.x=0;P.y=500;P.vx=0;P.vy=0;P.health=100;P.runCoins=0;P.dash=0;P.inv=0;P.onGround=true;P.step=0;worldTime=0;beast={x:0,y:-500,awake:false,timer:0};coins=[];particles=[];trees=[];const len=3000+Math.min(5,save.level-1)*350;for(let y=380;y>-len;y-=135)coins.push({x:Math.sin(y*.035)*155+Math.sin(y*.011)*45,y,r:13,taken:false});for(let y=350;y>-len;y-=95){trees.push({x:-250-Math.random()*100,y:y+Math.random()*50,s:0.8+Math.random()*.5});trees.push({x:250+Math.random()*100,y:y+Math.random()*50,s:0.8+Math.random()*.5})}$('hp').style.width='100%';$('status').textContent='😴 BEAST SLEEPING';$('warning').classList.add('hidden');$('pauseModal').classList.add('hidden');$('complete').classList.add('hidden');sync();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);toast('Use ▲ / ▼ to move forward & back')}
function finishDeath(){game=false;toast('The beast caught Ebram!');setTimeout(()=>show('menu'),800)}
function complete(){if(!game)return;game=false;$('runCoins').textContent=P.runCoins;$('totalCoins').textContent=save.coins;$('completeTitle').textContent='LEVEL '+save.level+' COMPLETE!';$('complete').classList.remove('hidden');beep(900)}
$('next').onclick=()=>{$('complete').classList.add('hidden');save.level++;persist();startGame()};$('menuBtn').onclick=()=>{$('complete').classList.add('hidden');show('menu')};$('pause').onclick=togglePause;$('resume').onclick=togglePause;$('quit').onclick=()=>{game=false;$('pauseModal').classList.add('hidden');show('menu')};function togglePause(){if(!game)return;paused=!paused;$('pauseModal').classList.toggle('hidden',!paused)}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','shift'].includes(k))e.preventDefault();keys[k]=true;if(e.code==='Space')jump();if(e.code==='ShiftLeft'||e.code==='ShiftRight')dash();if(k==='escape')togglePause()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function bindHold(btn,k){const on=e=>{e.preventDefault();keys[k]=true;btn.setPointerCapture?.(e.pointerId)};const off=e=>{e.preventDefault();keys[k]=false};btn.addEventListener('pointerdown',on);btn.addEventListener('pointerup',off);btn.addEventListener('pointercancel',off);btn.addEventListener('lostpointercapture',off)}document.querySelectorAll('[data-key]').forEach(b=>bindHold(b,b.dataset.key));
function jump(){if(game&&!paused&&P.onGround){P.vy=-620;P.onGround=false;beep(430)}}function dash(){if(game&&!paused&&P.dash<=0){P.dash=.28;beep(260)}}$('jump').onpointerdown=e=>{e.preventDefault();jump()};$('dash').onpointerdown=e=>{e.preventDefault();dash()};
function update(dt){worldTime+=dt;let ix=(keys.right||keys.d||keys.arrowright?1:0)-(keys.left||keys.a||keys.arrowleft?1:0);let iy=(keys.down||keys.s||keys.arrowdown?1:0)-(keys.up||keys.w||keys.arrowup?1:0);let speed=260*(save.owned.speed?1.2:1);if(P.dash>0)speed*=2.8;P.x+=ix*speed*dt;P.y+=iy*speed*dt;P.x=Math.max(-185,Math.min(185,P.x));P.y=Math.min(520,Math.max(-3350,P.y));P.dash=Math.max(0,P.dash-dt);P.inv=Math.max(0,P.inv-dt);if(ix)P.face=ix;P.step+=Math.abs(ix)+Math.abs(iy);beast.timer+=dt;const wake=Math.max(4,8-(save.level-1)*.4);if(!beast.awake&&beast.timer>wake){beast.awake=true;beast.timer=0;$('status').textContent='👹 BEAST AWAKE — RUN!';$('warning').classList.remove('hidden');setTimeout(()=>game&&$('warning').classList.add('hidden'),1200);beep(150)}if(beast.awake&&beast.timer>7.5){beast.awake=false;beast.timer=0;$('status').textContent='😴 BEAST SLEEPING'}if(beast.awake){const bx=P.x-beast.x,by=P.y-beast.y,d=Math.hypot(bx,by)||1,s=105+save.level*9;beast.x+=bx/d*s*dt;beast.y+=by/d*s*dt;if(d<60&&P.inv<=0){P.inv=1;P.health-=save.owned.shield?10:22;$('hp').style.width=Math.max(0,P.health)+'%';beep(100);if(P.health<=0){finishDeath();return}}}else{beast.x=Math.sin(worldTime*2)*55;beast.y=-500+Math.sin(worldTime*1.5)*15}for(const c of coins){if(!c.taken&&Math.hypot(P.x-c.x,P.y-c.y)<34){c.taken=true;const n=save.owned.forest?2:1;P.runCoins+=n;save.coins+=n;persist();beep(720);for(let i=0;i<7;i++)particles.push({x:c.x,y:c.y,vx:(Math.random()-.5)*100,vy:(Math.random()-.5)*100,t:.5})}}for(const q of particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.t-=dt}particles=particles.filter(q=>q.t>0);if(P.y<-3200)complete();$('coins').textContent=save.coins}
function draw(){const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);const cam=P.y-h*.63;ctx.fillStyle='#78d8ef';ctx.fillRect(0,0,w,h); // sky
// distant hills
ctx.fillStyle='#8acb86';for(let i=-1;i<5;i++){ctx.beginPath();ctx.arc(i*260-(cam*.03%260),h*.35,190,Math.PI,0);ctx.fill()}
ctx.fillStyle='#62a653';ctx.fillRect(0, h*.36,w,h*.64); // grass
ctx.fillStyle='#b88a5c';ctx.beginPath();ctx.moveTo(w/2-145,0);ctx.lineTo(w/2+145,0);ctx.lineTo(w/2+175,h);ctx.lineTo(w/2-175,h);ctx.fill();
for(const t of trees){const sy=t.y-cam;if(sy<-160||sy>h+160)continue;drawTree(w/2+t.x,sy,t.s)}
for(const c of coins)if(!c.taken){const sy=c.y-cam;if(sy>-30&&sy<h+30)drawCoin(w/2+c.x,sy,13)}
const py=P.y-cam;drawGate(w/2,-3200-cam);drawEbram(w/2+P.x,py);drawBeast(w/2+beast.x,beast.y-cam);for(const q of particles){ctx.globalAlpha=Math.max(0,q.t*2);ctx.fillStyle='#ffe36b';ctx.fillRect(w/2+q.x,q.y-cam,5,5)}ctx.globalAlpha=1}
function drawTree(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#70452d';ctx.fillRect(-12,20,24,75);ctx.fillStyle='#2f8e4d';ctx.beginPath();ctx.arc(0,0,58,0,7);ctx.arc(-38,30,43,0,7);ctx.arc(38,32,43,0,7);ctx.fill();ctx.fillStyle='#54aa5c';ctx.beginPath();ctx.arc(-20,-20,25,0,7);ctx.fill();ctx.restore()}
function drawCoin(x,y,r){ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(worldTime*5+y)*.25);ctx.fillStyle='#ffd34e';ctx.beginPath();ctx.arc(0,0,r,0,7);ctx.fill();ctx.strokeStyle='#b97922';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff3a2';ctx.beginPath();ctx.arc(-4,-4,4,0,7);ctx.fill();ctx.restore()}
function drawGate(x,y){ctx.save();ctx.translate(x,y);ctx.fillStyle='#28cfae';ctx.fillRect(-125,0,250,38);ctx.fillStyle='#126e68';ctx.fillRect(-110,38,25,120);ctx.fillRect(85,38,25,120);ctx.fillStyle='#eaffdc';ctx.font='900 16px Arial';ctx.textAlign='center';ctx.fillText('MYSTIC GATE',0,27);ctx.restore()}
function drawEbram(x,y){ctx.save();ctx.translate(x,y);if(P.inv>0&&Math.floor(P.inv*12)%2===0)ctx.globalAlpha=.45;const bob=Math.sin(P.step*.35)*3;ctx.translate(0,bob);ctx.fillStyle='#18213a';ctx.fillRect(-22,28,17,48);ctx.fillRect(5,28,17,48);ctx.fillStyle='#10131d';ctx.fillRect(-25,70,23,11);ctx.fillRect(3,70,25,11);ctx.fillStyle=save.owned.gold?'#e5bd45':'#2567c9';ctx.beginPath();ctx.roundRect(-39,-52,78,82,13);ctx.fill();ctx.fillStyle='#bd7f58';ctx.beginPath();ctx.arc(0,-82,30,0,7);ctx.fill();ctx.fillStyle='#1b151b';ctx.beginPath();ctx.arc(0,-103,31,Math.PI,0);ctx.fill();for(let a=-24;a<=24;a+=12){ctx.beginPath();ctx.arc(a,-103-Math.abs(a)*.15,8,0,7);ctx.fill()}ctx.fillStyle='#1a1014';ctx.fillRect(-19,-84,38,5);ctx.fillStyle='#bd7f58';ctx.fillRect(-47,-35,10,45);ctx.fillRect(37,-35,10,45);ctx.restore()}
function drawBeast(x,y){ctx.save();ctx.translate(x,y);const bob=Math.sin(worldTime*5)*3;ctx.translate(0,bob);ctx.fillStyle='#6e3b91';ctx.beginPath();ctx.ellipse(0,0,53,43,0,0,7);ctx.fill();ctx.fillStyle='#d39b4b';for(const s of[-30,30]){ctx.beginPath();ctx.moveTo(s-13,-24);ctx.lineTo(s,-76);ctx.lineTo(s+13,-24);ctx.fill()}ctx.fillStyle='#fff1a0';ctx.beginPath();ctx.arc(-18,-7,8,0,7);ctx.arc(18,-7,8,0,7);ctx.fill();ctx.fillStyle='#211526';ctx.beginPath();ctx.arc(-18,-7,3,0,7);ctx.arc(18,-7,3,0,7);ctx.fill();ctx.fillStyle='#412044';ctx.fillRect(-22,17,44,7);ctx.restore()}
function loop(t){if(!game)return;raf=requestAnimationFrame(loop);const dt=Math.min(.033,(t-last)/1000);last=t;if(!paused)update(dt);draw()}sync();
